### PR TITLE
Old RAM show wrong info, new dll fix this

### PR DESCRIPTION
**Pull request by turbosmurfen**
A friend to me have been asking to fix the RAM information for a long time. Now I have fixed this with the DLL-File and scripts changes. What I have heard doesn't nbs-irc no longer work because it's only using 32bit reading.

### CODE REVIEW

**Comment by ElectronicWar** [comment]
Did you patch the MemUsage.dll or was there a newer version available somewhere?

**Comment by turbosmurfen** [comment]
I created MemUsage.dll to use a way to detect RAM usage/total and percent. The darkenginex.dll was showing wrong information. Because someone in nbs-irc channel said it didn't support 64bit OS. 

Then there is a bad side that the dll I made works only for [Visual C++ Redistributable 2015-2022 x86/32bit](https://aka.ms/vs/17/release/vc_redist.x86.exe). Which only supports from Windows Vista and higher. So people that use the new dll and using less than Windows Vista wouldn't be able to use this.

Edit: Maybe there is possible to detect OS version in mIRC and use the old DLL for OS lower than Windows vista.

Edit 2: Here is an example:

Echo out darkenginex.dll with old information
```//echo -a Memory usage: $+($dedll(usedphysicalmem),/,$dedll(totalphysicalmem)) MB ( $+ $dedll(memoryload) $+ )```

```Memory usage: 1/2048 MB (32%)```

Echo out MemUsage.dll with updated information
```//echo -a Memory usage: $+($mudll(usedphysicalmem),/,$mudll(totalphysicalmem)) MB ( $+ $mudll(memoryload) $+ % $+ )```

```Memory usage: 5313/16300 MB (32%)```

**Comment by ElectronicWar** [comment]
With even Windows 7 end of life for over a year I don't have any issue that's not working on even older Windows versions.
I'll check it out and merge, thanks.

**Comment by turbosmurfen** [comment]
> With even Windows 7 end of life for over a year I don't have any issue that's not working on even older Windows versions. I'll check it out and merge, thanks.

The DLL works for Vista, 7, 8.1, 10, 11. I use Windows 11 and it works great for me. But the [Visual C++ Redistributable 2015-2022 x86/32bit](https://aka.ms/vs/17/release/vc_redist.x86.exe) need to be installed to be able to use the DLL.

**Pull request closed without merging**
